USE DATABASE SNOW_PIPE;

--CREATING THE TABLE

CREATE OR REPLACE TABLE HEALTHCARE(
Patientid VARCHAR(15),
gender CHAR(8),
age VARCHAR(5) ,
hypertension CHAR(20),
heart_disease CHAR(20),
ever_married CHAR(30),
work_type VARCHAR(60),
Residence_type CHAR(30) ,
avg_glucose_level VARCHAR(20),
bmi VARCHAR(20) ,
smoking_status VARCHAR(20),
stroke CHAR(20)
);

SELECT * FROM HEALTHCARE;


--CREATE STORAGE INTEGRATION

CREATE OR REPLACE STORAGE INTEGRATION S3_SPIPE_AD
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER= S3
ENABLED= TRUE
STORAGE_AWS_ROLE_ARN ='arn:aws:iam::319724511632:role/snowpipeuser'
STORAGE_ALLOWED_LOCATIONS=('s3://patientawssnowpipe/');

--DESCRIBE STORAGE

DESC INTEGRATION S3_SPIPE_AD;

--CREATE STAGE

CREATE OR REPLACE STAGE PATIENT_SNOW_STAGE
URL = 's3://patientawssnowpipe' --NAME OF BUCKET WE HAVE CREATED
--credentials=(aws_key_id ='AKIAUU4IQ4GIAWJRFVHO' aws_secret_key='TzsUiDvX34xYeUjhRqhgdI9hj2bsPcWYZaTz0k26' )
file_format = CSV
storage_integration=S3_SPIPE_AD;

--CREATE SNOWPIPE THAT RECEOGNISES CSV THAT ARE INGESTED FROM EXTERNAL STAGE AND COPIES THE DATA INTO PATIENT TABLE

CREATE OR REPLACE PIPE PATIENT_SNOWPIPE AUTO_INGEST = TRUE AS 
COPY INTO "SNOW_PIPE"."PUBLIC"."HEALTHCARE"
FROM @PATIENT_SNOW_STAGE
FILE_FORMAT = CSV;

SHOW PIPES;

ALTER PIPE PATIENT_SNOWPIPE REFRESH;

SELECT count(*) FROM HEALTHCARE;


SELECT * FROM HEALTHCARE;



